[project]
name = "cfc-python"
version = "0.1.0"
description = "Python-translation of Mamassian & de Gardelle (2022) CFC model toolbox"
readme = "README.md"
authors = [
    { name = "ninaedgley", email = "nina.edgley@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.24",
    "scipy>=1.9",
]

[project.scripts]
cfc-python = "cfc_python:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
